# Uncomment the next line to define a global platform for your project
platform :ios, '10.3'

target 'iOS-WebSocket' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Starscream', :git => 'https://github.com/daltoniam/Starscream.git', :branch => 'swift3' 

  # Pods for iOS-WebSocket

  target 'iOS-WebSocketTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iOS-WebSocketUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
